'use strict';

const path = require('path');

/**
 * Central configuration. Values can be overridden via CLI flags (see server.js)
 * or environment variables. Keep this the single source of truth for tunables.
 */
const ROOT = path.resolve(__dirname, '..');

const config = {
  // Proxy listen port for the HTTP CONNECT forward-proxy.
  port: envInt('SRP_PORT', 8787),
  host: process.env.SRP_HOST || '127.0.0.1',

  // Local CA material (generated by src/tools/gen-ca.js).
  caDir: process.env.SRP_CA_DIR || path.join(ROOT, 'ca'),
  caCertFile: 'ca.pem',
  caKeyFile: 'ca.key.pem',

  // Hosts to TLS-intercept. Everything else is blind-tunnelled. Supports exact
  // hostnames and leading-wildcard suffixes (".example.com").
  allowlist: [
    'api.openai.com',
    'api.anthropic.com',
    'generativelanguage.googleapis.com',
    'api.githubcopilot.com',
    'copilot-proxy.githubusercontent.com',
  ],

  // Detection thresholds.
  entropy: {
    // Minimum token length before entropy is even considered.
    minLength: 20,
    // Shannon entropy (bits/char) threshold for base64-ish tokens.
    base64Threshold: 4.0,
    // Threshold for hex tokens (lower alphabet => lower max entropy).
    hexThreshold: 3.0,
  },

  // Body-size guardrails.
  limits: {
    // Above this, skip JSON parsing/redaction and pass the body through
    // untouched (huge uploads are unlikely conversation payloads).
    maxRedactBytes: 8 * 1024 * 1024,
  },

  // Policy: secret types that MUST be tokenizable. If detected at high
  // confidence but a fake cannot be produced, the request is blocked
  // (fail-closed) rather than forwarded with the real value.
  failClosedTypes: new Set([
    'aws-secret-access-key',
    'aws-access-key-id',
    'github-pat',
    'openai-key',
    'anthropic-key',
    'stripe-secret-key',
    'private-key-pem',
    'gcp-service-account-key',
  ]),

  // Types that are redacted but never cause a block on their own (avoid
  // over-blocking legitimate high-entropy text such as hashes/UUIDs).
  redactOnlyTypes: new Set([
    'high-entropy-blob',
  ]),

  // Audit log directory (JSONL, fingerprints only — never raw secrets).
  auditDir: process.env.SRP_AUDIT_DIR || path.join(ROOT, 'audit'),

  // Salt for fingerprint hashing. Generated per-process if not provided so
  // fingerprints are not correlatable across restarts unless pinned.
  fingerprintSalt: process.env.SRP_FP_SALT || null,

  // Verbose logging to stderr.
  verbose: /^(1|true|yes)$/i.test(process.env.SRP_VERBOSE || ''),
};

function envInt(name, fallback) {
  const v = process.env[name];
  if (v == null || v === '') return fallback;
  const n = parseInt(v, 10);
  return Number.isFinite(n) ? n : fallback;
}

module.exports = config;
